### ISSUE TITLE
Tornar instalável pelo Boss.

### ISSUE THREAD

**Issue by marvinbraga** [marvinbraga/Marvin.IA#30]
Para Matheus Hunsche.
Obrigado e abraços.

**Comment by snakeice** [comment]
Basicamente foi mudado as tags do projeto para o padrão do [Semantic Versioning](https://semver.org/)
E foi feito um pequeno ajuste referente ao boss onde não estava conseguindo encontrar os objetos do repositório baseando-se no hash da versão, com isso passou para o uso do próprio nome do tag.
Ainda precisamos de algumas melhorias do lado do boss para efetuar a compilação do projeto (no caso o Marvin.IA), oque deve ocorrer nos próximos dias.. Assim que sair mando noticias. 

Obrigado ^^.

**Comment by marvinbraga** [comment]
Excelente! Parabéns e obrigado. Fico no aguardo.

**Comment by snakeice** [comment]
Uma duvida me surgiu, devo compilar Marvin.Core.dproj e Marvin.Core.IA.Connectionist.dproj para utilização da dependência ou somente Marvin.Core.dproj? Pois estou fazendo algumas refatorações no gerenciamento de compilação e librarypath.

**Comment by marvinbraga** [comment]
Tem que compilar os dois, pois, o Marvin.Core.IA.Connectionist.dproj depende do Marvin.Core.dproj.

**Comment by snakeice** [comment]
Compilação ajustada e projeto 100% instalável pelo [Boss](https://github.com/HashLoad/boss).
